import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 30,
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
    paddingBottom: 5,
  },
  statLabel: {
    fontSize: 12,
    color: '#555',
  },
  statValue: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  summaryTitle: {
    fontSize: 18,
    marginTop: 20,
    marginBottom: 10,
    fontWeight: 'bold',
  },
  summaryText: {
    fontSize: 12,
    lineHeight: 1.5,
    textAlign: 'justify',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#AAA',
  },
});

interface AnalyticsReportPdfProps {
  startDate: Date;
  endDate: Date;
  totalSubmissions: number;
  approvalRate: number;
  topLetterType: string;
  aiSummary: string;
}

export const AnalyticsReportPdf = ({
  startDate,
  endDate,
  totalSubmissions,
  approvalRate,
  topLetterType,
  aiSummary,
}: AnalyticsReportPdfProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Monthly Performance Report</Text>
      
      <View style={styles.section}>
        <Text style={{ fontSize: 14, marginBottom: 20, textAlign: 'center', color: '#666' }}>
          {startDate.toLocaleDateString()} - {endDate.toLocaleDateString()}
        </Text>

        <View style={styles.statRow}>
          <Text style={styles.statLabel}>Total Submissions</Text>
          <Text style={styles.statValue}>{totalSubmissions}</Text>
        </View>

        <View style={styles.statRow}>
          <Text style={styles.statLabel}>Approval Rate</Text>
          <Text style={styles.statValue}>{approvalRate.toFixed(1)}%</Text>
        </View>

        <View style={styles.statRow}>
          <Text style={styles.statLabel}>Most Frequent Letter Type</Text>
          <Text style={styles.statValue}>{topLetterType}</Text>
        </View>

        <Text style={styles.summaryTitle}>AI Analysis</Text>
        <Text style={styles.summaryText}>{aiSummary}</Text>
      </View>

      <Text style={styles.footer}>
        Generated by Document Submission System on {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);
